version: '3.8'

services:
  python-sandbox:
    build: .
    container_name: python-sandbox
    ports:
      - "7111:7111"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      # Optional: Mount a volume for persistent logs
      - ./logs:/var/log/nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7111/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
